language: node_js
node_js:
- "8"
sudo: false
cache:
- node_modules
script:
- npm test
env:
  global:
  - NODE_ENV=test
  - GOOGLE_CLIENT_EMAIL=dGVzdAo=
  - GOOGLE_PRIVATE_KEY=dGVzdAo=
  - GOOGLE_VIEW_ID=test
  - GOOGLE_ANALYTICS_TIMEZONE=America/New_York